"""add adaptive performance streaks

Revision ID: 669799faef60
Revises: 9b58aeb33f61
Create Date: 2026-08-16 14:53:03.816463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "669799faef60"
down_revision: Union[str, Sequence[str], None] = "9b58aeb33f61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_sessions",
        sa.Column(
            "poor_streak",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )

    op.add_column(
        "interview_sessions",
        sa.Column(
            "strong_streak",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "interview_sessions",
        "strong_streak",
    )

    op.drop_column(
        "interview_sessions",
        "poor_streak",
    )
    # ### end Alembic commands ###