"""add current question to interview sessions

Revision ID: 93aaf95fad92
Revises: 669799faef60
Create Date: 2026-08-16 16:31:16.457138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93aaf95fad92'
down_revision: Union[str, Sequence[str], None] = '669799faef60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('current_question_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_interview_sessions_current_question_id'), 'interview_sessions', ['current_question_id'], unique=False)
    op.create_foreign_key(None, 'interview_sessions', 'questions', ['current_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_sessions_current_question_id'), table_name='interview_sessions')
    op.drop_column('interview_sessions', 'current_question_id')
    # ### end Alembic commands ###
