"""add final interview report

Revision ID: fd24c1c1c69a
Revises: 93aaf95fad92
Create Date: 2026-08-16 16:58:51.613999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd24c1c1c69a'
down_revision: Union[str, Sequence[str], None] = '93aaf95fad92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('final_summary', sa.Text(), nullable=True))
    op.add_column('interview_sessions', sa.Column('final_strengths', sa.Text(), nullable=True))
    op.add_column('interview_sessions', sa.Column('final_weaknesses', sa.Text(), nullable=True))
    op.add_column('interview_sessions', sa.Column('technical_assessment', sa.Text(), nullable=True))
    op.add_column('interview_sessions', sa.Column('communication_assessment', sa.Text(), nullable=True))
    op.add_column('interview_sessions', sa.Column('problem_solving_assessment', sa.Text(), nullable=True))
    op.add_column('interview_sessions', sa.Column('final_recommendations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'final_recommendations')
    op.drop_column('interview_sessions', 'problem_solving_assessment')
    op.drop_column('interview_sessions', 'communication_assessment')
    op.drop_column('interview_sessions', 'technical_assessment')
    op.drop_column('interview_sessions', 'final_weaknesses')
    op.drop_column('interview_sessions', 'final_strengths')
    op.drop_column('interview_sessions', 'final_summary')
    # ### end Alembic commands ###
